### ISSUE TITLE
milestone overview 0.1.0

### ISSUE THREAD

**Issue by bruggerk** [neuromics/cromwell-utils#3]
- cromwell-cli
  - [x] submit workflow
  - [x] list workflows
  - [x] monitor workflows
  - [x] cleanup tmpfiles from finished/failed workflows
  - [x] ping cromwell server
  - [x] zip wdl pacakage
- nsm-analysis
  - [x] exome
  - [x] exome (bulk)
  - [x]  Salmon
  - [x]  bam -> gvcf+vcf
  - [x] bams_to_ubams
  - [x] fqs_to_ubams
- Misc
  - [x]  cromwell wrapper
  - [x]  picard wrapper
  - [x]  womtool wrapper
