### ISSUE TITLE
milestone overview 0.3.0

### ISSUE THREAD

**Issue by bruggerk** [neuromics/cromwell-utils#9]
- DNA
  - [ ]  Annotate vcf (nirvana)
- RNA
  - [ ]  Star
  - [ ]  FeatureCounts
- Variant calling
  - [ ]  star-alignment -> gvcf + vcf
  - [ ]  bams -> gvcfs + vcfs (?)

- Utils
  - [ ] bam split (for parallel running of big samples)
  
- Saved for later Milestones 

  - [ ]  Genome/Exome multiple input samples
